services:
    gateway:
        build:
            context: .
            dockerfile: ./apps/gateway/Dockerfile
            target: development
        command: npm run start:dev gateway
        ports:
            - '${GATEWAY_PORT}:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/gateway/.env
    auth:
        build:
            context: .
            dockerfile: ./apps/auth/Dockerfile
            target: development
        command: npm run start:dev auth
        ports:
            - '${AUTH_PORT}:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/auth/.env
    codesaga:
        build:
            context: .
            dockerfile: ./apps/codesaga/Dockerfile
            target: development
        command: npm run start:dev codesaga
        ports:
            - '${CODESAGA_PORT}:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/codesaga/.env
    llama:
        build:
            context: .
            dockerfile: ./apps/llama/Dockerfile
            target: development
        command: npm run start:dev llama
        ports:
            - '${LLAMA_PORT}:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/llama/.env
    chat:
        build:
            context: .
            dockerfile: ./apps/chat/Dockerfile
            target: development
        command: npm run start:dev chat
        ports:
            - '${CHAT_PORT}:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/chat/.env
    mysql:
        image: mysql:5.7
        platform: linux/amd64
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    'mysql',
                    '-u',
                    'root',
                    '-p${MYSQL_PASSWORD}',
                ]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
        env_file:
            - ./apps/gateway/.env
        environment:
            TZ: Asia/Seoul
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    mongo:
        image: mongo:8
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - ./mongo/data:/data/db
        command: mongod --quiet --logpath /dev/null
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
    redis:
        image: redis:7-alpine
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        restart: always
        command: redis-server --appendonly yes
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    # webui:
    #     image: ghcr.io/open-webui/open-webui:main
    #     # platform: linux/amd64
    #     restart: always
    #     ports:
    #         - '80:8080'
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     volumes:
    #         - ./webui:/app/backend/data
