// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: proto/auth.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface FindOrCreateUserRequest {
  id: string;
  nodeId: string;
  avatarUrl: string;
  login: string;
  name: string;
}

export interface FindOrCreateUserResponse {
  id: string;
}

export interface IssueTokenByGithubIdRequest {
  id: string;
}

export interface IssueTokenByGithubIdResponse {
  accessToken: string;
  refreshToken: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  findOrCreateUser(request: FindOrCreateUserRequest, metadata?: Metadata): Observable<FindOrCreateUserResponse>;

  issueTokenByGithubId(
    request: IssueTokenByGithubIdRequest,
    metadata?: Metadata,
  ): Observable<IssueTokenByGithubIdResponse>;
}

export interface AuthServiceController {
  findOrCreateUser(
    request: FindOrCreateUserRequest,
    metadata?: Metadata,
  ): Promise<FindOrCreateUserResponse> | Observable<FindOrCreateUserResponse> | FindOrCreateUserResponse;

  issueTokenByGithubId(
    request: IssueTokenByGithubIdRequest,
    metadata?: Metadata,
  ): Promise<IssueTokenByGithubIdResponse> | Observable<IssueTokenByGithubIdResponse> | IssueTokenByGithubIdResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOrCreateUser", "issueTokenByGithubId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
